gpus:
  "0":
    - name: Qwen/Qwen1.5-0.5B
      base_url: http://localhost:8005
    - name: Qwen/Qwen2.5-1.5B-Instruct
      base_url: http://localhost:8006
  "1":
    - name: Qwen/Qwen1.5-0.5B-Chat-GPTQ-Int4
      base_url: http://localhost:8007
    - name: Qwen/Qwen2.5-0.5B-Instruct-AWQ
      base_url: http://localhost:8008
